table Sales
	lineageTag: a8c377ce-4d50-438f-8719-83999a5c58af

	/// Total revenue across all sales channels (Internet and Reseller). Primary top-line metric used in most reports.
	measure 'Total Sales' = SUM(Sales[Sales Amount])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a1e4f7b2-3c8d-4f6a-9b2e-d5c7a8f01234

	/// Aggregated cost of goods sold across all product lines and channels.
	measure 'Total Cost' = SUM(Sales[Total Product Cost])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b2f5a8c3-4d9e-5a7b-0c3f-e6d8b9a12345

	/// Revenue minus cost of goods sold. Key profitability indicator before operating expenses.
	measure 'Gross Profit' = [Total Sales] - [Total Cost]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c3a6b9d4-5e0f-6b8c-1d4a-f7e9c0b23456

	measure 'Order Qty' = SUM(Sales[Order Quantity])
		formatString: #,0
		lineageTag: d4b7c0e5-6f1a-7c9d-2e5b-a8f0d1c34567

	measure 'Gross Profit Margin' = DIVIDE([Gross Profit], [Total Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e5c8d1f6-7a2b-8d0e-3f6c-b9a1e2d45678

	measure sales_ytd = TOTALYTD([Total Sales], 'Date'[Date])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f6d9e2a7-8b3c-9e1f-4a7d-c0b2f3e56789

	measure Sales_MTD = TOTALMTD([Total Sales], 'Date'[Date])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a7e0f3b8-9c4d-0f2a-5b8e-d1c3a4f67890

	measure 'Sum of Transactions' = COUNTROWS(Sales)
		formatString: #,0
		lineageTag: b8f1a4c9-0d5e-1a3b-6c9f-e2d4b5a78901

	measure 'Sales per Active Day' =
			VAR _TotalSales =
			    CALCULATE(
			        SUMX(
			            Sales,
			            Sales[Sales Amount]
			        )
			    )
			VAR _ActiveDays =
			    COUNTROWS(
			        FILTER(
			            VALUES('Date'[Date]),
			            NOT(ISBLANK(
			                CALCULATE(
			                    SUM(Sales[Sales Amount])
			                )
			            ))
			        )
			    )
			RETURN
			    IF(
			        _ActiveDays > 0,
			        _TotalSales / _ActiveDays,
			        BLANK()
			    )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c9a2b5d0-1e6f-2b4c-7d0a-f3e5c6b89012

	/// Year-to-Date Sales basierend auf Total Sales
	measure 'YTD Sales' = CALCULATE([Total Sales], DATESYTD('Date'[Date]))
		formatString: #,0.00 €
		lineageTag: 6acb2265-4cd1-4a35-b73b-1689b0694d8a

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e77a082c-ada4-4b9a-a885-e96fe0e1264c
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c23cc51b-4fe2-48ad-9242-7ab46bf18be5
		summarizeBy: none
		sourceColumn: ResellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0ed0ec8e-c6c5-49de-a887-db18639dbcb8
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: db045ae1-0565-4727-80bd-d169544ff1b3
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5283270f-0706-47f9-b87a-64cd62506dc4
		summarizeBy: none
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d23a2d68-4876-4e92-b8d6-541a48b19f44
		summarizeBy: count
		sourceColumn: DueDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8d9f6621-7e18-4e91-99fa-a28987a5e4d1
		summarizeBy: count
		sourceColumn: ShipDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8a56e5c1-cdd4-4067-9c9a-32508b3a104f
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		formatString: #,0
		lineageTag: 541580a9-ec67-4289-80c6-d90978e0e4c9
		summarizeBy: sum
		sourceColumn: Order Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0c21edbd-c779-4f40-bf85-46b5f617988d
		summarizeBy: average
		sourceColumn: Unit Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Extended Amount'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b60f89ae-9208-46ee-b461-3ec3eb0ac465
		summarizeBy: sum
		sourceColumn: Extended Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Product Standard Cost'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 20f728ab-06bd-4c1b-a639-97b61f53671e
		summarizeBy: sum
		sourceColumn: Product Standard Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Total Product Cost'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a960b8cb-8280-4ba5-b3d4-5a0e42515fe3
		summarizeBy: sum
		sourceColumn: Total Product Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Sales Amount'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: db18df6f-233c-40de-9a3c-cded8a26f356
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Unit Price Discount Pct'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b58c1ed6-6ddc-4d54-aea8-6cb0d23795c5
		summarizeBy: none
		sourceColumn: Unit Price Discount Pct

		annotation SummarizationSetBy = User

	column CurrencyKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c4e09677-fca3-4c17-9a9b-16097fe3d324
		summarizeBy: none
		sourceColumn: CurrencyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Sales-1c496a38-f0f4-4d25-b987-657177c38553 = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_vFactSales = Source{[Schema="dbo",Item="vFactSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_vFactSales,{"SalesOrderLineKey", "ResellerKey", "CustomerKey", "ProductKey", "OrderDateKey", "DueDateKey", "ShipDateKey", "CurrencyKey", "SalesTerritoryKey", "OrderQuantity", "UnitPrice", "ExtendedAmount", "UnitPriceDiscountPct", "ProductStandardCost", "TotalProductCost", "SalesAmount"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"OrderQuantity", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ExtendedAmount", "Extended Amount"}, {"OrderQuantity", "Order Quantity"}, {"ProductStandardCost", "Product Standard Cost"}, {"SalesAmount", "Sales Amount"}, {"TotalProductCost", "Total Product Cost"}, {"UnitPrice", "Unit Price"}, {"UnitPriceDiscountPct", "Unit Price Discount Pct"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

